on:
  workflow_dispatch:
jobs:
    command_example:
        runs-on: ubuntu-latest
        steps:
          - name: Run example command
            run: |
                deprecated=true
                if [ "$deprecated" = true ]; then
                  echo "::warning::This command is deprecated and will be removed in future versions."
                fi

          - name: Set API KEY
            run: echo "API_KEY=your_api_key_here" >> $GITHUB_ENV
          - name: Use API KEY
            run: echo "The API key is $API_KEY"
            
          - name: Check if a file esists
            run: |
                if [ -f "./config.yaml" ]; then
                  echo "::debug::config.yaml exists."
                else
                  echo "::error::config.yaml does not exist."